"""update connections table

Revision ID: db1a473220e1
Revises: 1a7c470d5142
Create Date: 2022-12-22 10:58:25.603879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1a473220e1'
down_revision = '1a7c470d5142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'created_at')
    # ### end Alembic commands ###
