"""add profiles table

Revision ID: 3ddda6112897
Revises: db1a473220e1
Create Date: 2023-01-03 11:10:20.187254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ddda6112897'
down_revision = 'db1a473220e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_image_url', sa.String(length=1500), server_default='https://static.licdn.com/sc/h/3h0vrtch1zepjr4p54aja8i9x', nullable=True),
    sa.Column('banner_image_url', sa.String(length=1500), server_default='https://static.licdn.com/sc/h/55k1z8997gh8dwtihm11aajyq', nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    # ### end Alembic commands ###
